package com.se100.clinic.doctor;

import com.se100.clinic.shared.BaseAuditEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Specialty entity (ChuyenKhoa) — e.g. internal medicine, cardiology, pediatrics.
 *
 * <p><b>Why package-private</b> (no {@code public} before {@code class}): other modules (e.g.
 * {@code booking}) must not load this entity or query it through {@code SpecialtyRepository}. They
 * call {@link SpecialtyService} and receive {@link SpecialtyDtos.SpecialtyResponse}, or store just
 * a {@code Long specialtyId} — never a JPA relation ({@code @ManyToOne}) pointing here.
 *
 * <p>Comparison:
 *
 * <ul>
 *   <li><b>NestJS:</b> a TypeORM {@code @Entity()} class or a Prisma {@code model}. TypeScript can
 *       only hide things per file (export or not); Java's package-private hides per package.
 *   <li><b>ASP.NET Core:</b> an EF Core entity. The closest C# modifier is {@code internal}, but
 *       that covers the whole assembly; package-private is narrower — one package only.
 * </ul>
 *
 * <p>Annotations: {@code @Entity} marks a JPA-managed class; {@code @Table} names the table;
 * {@code @Id} + {@code @GeneratedValue(IDENTITY)} = primary key generated by the database identity
 * column; {@code @Column} maps constraints (length, nullability) that must match the Flyway
 * migration.
 */
@Entity
@Table(name = "specialties")
class Specialty extends BaseAuditEntity {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /** Unique business code used in URLs/reports, e.g. {@code "NOI_TONG_QUAT"}. */
  @Column(nullable = false, unique = true, length = 50)
  private String code;

  @Column(nullable = false, length = 200)
  private String name;

  @Column(columnDefinition = "text")
  private String description;

  /** Soft-disable flag. We never hard-delete, so historical references stay valid. */
  @Column(nullable = false)
  private boolean active = true;

  /** Required by JPA: Hibernate instantiates entities via reflection with a no-arg constructor. */
  protected Specialty() {}

  Specialty(String code, String name, String description) {
    this.code = code;
    this.name = name;
    this.description = description;
    this.active = true;
  }

  Long getId() {
    return id;
  }

  String getCode() {
    return code;
  }

  String getName() {
    return name;
  }

  String getDescription() {
    return description;
  }

  boolean isActive() {
    return active;
  }

  void rename(String name, String description) {
    this.name = name;
    this.description = description;
  }

  void setActive(boolean active) {
    this.active = active;
  }
}
